export const ADD_STOCK_IN_ORDER = '@@stocks/ADD_STOCK_IN_ORDER';
export const REMOVE_STOCK_IN_ORDER = '@@stocks/REMOVE_STOCK_IN_ORDER';
export const SELECT_STOCK_IN_ORDER = '@@stocks/SELECT_STOCK_IN_ORDER';
export const UNSELECT_STOCK_IN_ORDER = '@@stocks/UNSELECT_STOCK_IN_ORDER';
export const UPDATE_STOCK_ORDER_STATUS = '@@stocks/UPDATE_STOCK_ORDER_STATUS';
export const UPDATE_STOCK_ORDER_EXECUTION_MODE =
  '@@stocks/UPDATE_STOCK_ORDER_EXECUTION_MODE';
export const UPDATE_STOCK_ORDER_ORDER_PRICE =
  '@@stocks/UPDATE_STOCK_ORDER_ORDER_PRICE';
export const UPDATE_STOCK_ORDER_SHARE_AMOUNT =
  '@@stocks/UPDATE_STOCK_ORDER_SHARE_AMOUNT';
export const PLACE_STOCK_ORDER = '@@stocks/PLACE_STOCK_ORDER';
export const PLACE_STOCK_ORDER_SUCCESS = '@@stocks/PLACE_STOCK_ORDER_SUCCESS';
export const PLACE_STOCK_ORDER_ERROR = '@@stocks/PLACE_STOCK_ORDER_ERROR';
export const ACKNOWLEDGE_STOCK_ORDER_ERROR =
  '@@stocks/ACKNOWLEDGE_STOCK_ORDER_ERROR';
